name: Appium Android

on:
  workflow_dispatch:
    inputs:
      allure:
        type: boolean
        description: Generar reporte Allure
        default: true
      extent:
        type: boolean
        description: Generar reporte Extent
        default: true
      cucumber:
        type: boolean
        description: Generar reporte Cucumber
        default: true
      recorder:
        type: boolean
        description: Grabar la ejecución
        default: true

jobs:
  appium:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 27 ]
        target: [ default ]
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.302+8'
          distribution: 'temurin'
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: |
          ls
          npm install -g appium@v1.22.3
          appium -v
          appium --chromedriver-executable ./test/java/resources/app/chromedriver &>/dev/null &  &>/dev/null &
      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{matrix.api-level}}
          avd-name: Pixel
          profile: pixel
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: mvn test

      - name: Generate artifact for video report
        uses: actions/upload-artifact@v2
        if: ${{ github.event.inputs.recorder == 'true' }}
        with:
          name: video_report
          path: ./Android_Pixel/Videos/

      - name: Generate artifact for allure report
        uses: actions/upload-artifact@v2
        if: ${{ github.event.inputs.allure == 'true' }}
        with:
          name: allure_report
          path: ./allure-results

      - name: Upload artifact for extent reports
        uses: actions/upload-artifact@v3
        if: ${{ github.event.inputs.extent == 'true' }}
        with:
          name: Extent
          path: ./Reports

      - name: Upload artifact for cucumber reports
        uses: actions/upload-artifact@v3
        if: ${{ github.event.inputs.cucumber == 'true' }}
        with:
          name: cucumber_report
          path: ./target_TestNG/Pixel
